name: Code Quality Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  code-quality-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dev dependencies
        run: |
          make pip-install-dev

      - name: Run linter check
        run: |
          echo "ğŸ” Running linter check..."
          make lint-check

      - name: Run type check
        run: |
          echo "ğŸ”  Running type check..."
          make type-check

      - name: Run pre-commit hooks checks
        run: |
          echo "ğŸ”  Running pre-commit hook checks..."
          make hooks-check

      - name: Detecting secrets
        run: |
          echo "ğŸ”  Detecting secrets..."
          make detect-secrets

      - name: Security checks
        run: |
          echo "ğŸ”  Running security checks..."
          make detect-secrets
